### ISSUE TITLE
Brew Log - add description to brew log creator when there are no active recipes

### ISSUE THREAD

**Issue by FortMyersBrewing** [dphaener/fermentable-issues#3]
Added new recipes, went to add brew log drop-down list empty.
Steps to reproduce: Add new recipes, go to Brew Logs click +, drop-down empty 

OS: OS X Yosemite
Ver: 10.10
Browser: Google Chrome, Version 39.0.2171.71 (64-bit)
Browser: Firefox 33.1.1

**Comment by dphaener** [comment]
Just had a look at your account. Few things to mention here.

All of your recipes are currently "disabled" (look at the blue button next to the name in the recipe editor), only "active" recipes will be available to brew.

There are certain requirements that must be met in order to "activate" a recipe:

* You must have all ingredients in inventory(there's a status icon next to each ingredient with a tooltip giving you the current status.
* You must have at least one grain, one hop and one mash rest added to the recipe.

Seems like there needs to be some sort of explanation about this in the app.

**Comment by dphaener** [comment]
Closed
